spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/apiserver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.MariaDB106Dialect



    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
        format_sql: true
        show_sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      location: /Users/jungwoo/Desktop/dev/SpringBootApiServer/backend/src/main/resources/img
      file-size-threshold: 1MB


logging.level:
  org.hibernate.type: trace

security:
  jwt:
    token:
      secretKey: secretkey
      expire: 1800000
#      expire: 60000//1분



